"""
Sri Lanka Locations Database
All major tourist locations with coordinates, categories, visit durations, and costs.
"""

SRI_LANKA_LOCATIONS = [
    # Cultural Triangle
    {
        "id": "sigiriya",
        "name": "Sigiriya Rock Fortress",
        "lat": 7.9573,
        "lng": 80.7600,
        "category": "cultural",
        "region": "cultural_triangle",
        "visit_duration_hours": 3.0,
        "entry_fee_usd": 30,
        "best_time": "morning",
        "tags": ["history", "climbing", "photography", "UNESCO"],
        "description": "Ancient rock fortress with panoramic views and frescoes",
        "difficulty": "moderate",
        "ocean_traits": ["openness", "conscientiousness"]
    },
    {
        "id": "dambulla",
        "name": "Dambulla Cave Temple",
        "lat": 7.8567,
        "lng": 80.6490,
        "category": "cultural",
        "region": "cultural_triangle",
        "visit_duration_hours": 2.0,
        "entry_fee_usd": 15,
        "best_time": "morning",
        "tags": ["history", "religion", "caves", "UNESCO"],
        "description": "Ancient Buddhist cave temple complex",
        "difficulty": "easy",
        "ocean_traits": ["openness", "agreeableness"]
    },
    {
        "id": "anuradhapura",
        "name": "Anuradhapura Ancient City",
        "lat": 8.3114,
        "lng": 80.4037,
        "category": "cultural",
        "region": "cultural_triangle",
        "visit_duration_hours": 5.0,
        "entry_fee_usd": 25,
        "best_time": "morning",
        "tags": ["history", "ruins", "religion", "UNESCO"],
        "description": "Sacred ancient city with stupas and ruins",
        "difficulty": "easy",
        "ocean_traits": ["openness", "conscientiousness"]
    },
    {
        "id": "polonnaruwa",
        "name": "Polonnaruwa Ancient City",
        "lat": 7.9403,
        "lng": 81.0188,
        "category": "cultural",
        "region": "cultural_triangle",
        "visit_duration_hours": 4.0,
        "entry_fee_usd": 25,
        "best_time": "morning",
        "tags": ["history", "ruins", "cycling", "UNESCO"],
        "description": "Well-preserved medieval capital with Buddha statues",
        "difficulty": "easy",
        "ocean_traits": ["openness", "conscientiousness"]
    },
    {
        "id": "kandy",
        "name": "Kandy Temple of the Tooth",
        "lat": 7.2936,
        "lng": 80.6413,
        "category": "cultural",
        "region": "hill_country",
        "visit_duration_hours": 2.5,
        "entry_fee_usd": 15,
        "best_time": "morning",
        "tags": ["religion", "culture", "ceremony", "UNESCO"],
        "description": "Famous Buddhist temple housing Buddha's tooth relic",
        "difficulty": "easy",
        "ocean_traits": ["agreeableness", "openness"]
    },
    # Hill Country
    {
        "id": "ella",
        "name": "Ella Nine Arch Bridge",
        "lat": 6.8667,
        "lng": 81.0466,
        "category": "nature",
        "region": "hill_country",
        "visit_duration_hours": 3.0,
        "entry_fee_usd": 0,
        "best_time": "morning",
        "tags": ["hiking", "photography", "trains", "tea"],
        "description": "Iconic colonial railway bridge surrounded by tea plantations",
        "difficulty": "easy",
        "ocean_traits": ["openness", "extraversion"]
    },
    {
        "id": "adams_peak",
        "name": "Adam's Peak (Sri Pada)",
        "lat": 6.8096,
        "lng": 80.4994,
        "category": "nature",
        "region": "hill_country",
        "visit_duration_hours": 8.0,
        "entry_fee_usd": 0,
        "best_time": "night",
        "tags": ["hiking", "spiritual", "sunrise", "pilgrimage"],
        "description": "Sacred mountain peak with stunning sunrise views",
        "difficulty": "hard",
        "ocean_traits": ["openness", "conscientiousness", "extraversion"]
    },
    {
        "id": "nuwara_eliya",
        "name": "Nuwara Eliya Tea Plantations",
        "lat": 6.9497,
        "lng": 80.7891,
        "category": "nature",
        "region": "hill_country",
        "visit_duration_hours": 4.0,
        "entry_fee_usd": 5,
        "best_time": "morning",
        "tags": ["tea", "nature", "colonial", "photography"],
        "description": "Little England with tea estates and colonial architecture",
        "difficulty": "easy",
        "ocean_traits": ["openness", "agreeableness"]
    },
    {
        "id": "horton_plains",
        "name": "Horton Plains & World's End",
        "lat": 6.8024,
        "lng": 80.8046,
        "category": "nature",
        "region": "hill_country",
        "visit_duration_hours": 4.0,
        "entry_fee_usd": 25,
        "best_time": "morning",
        "tags": ["hiking", "wildlife", "nature", "photography"],
        "description": "Scenic plateau with dramatic cliff drop at World's End",
        "difficulty": "moderate",
        "ocean_traits": ["openness", "conscientiousness"]
    },
    # Beaches & Coast
    {
        "id": "mirissa",
        "name": "Mirissa Beach",
        "lat": 5.9483,
        "lng": 80.4515,
        "category": "beach",
        "region": "south_coast",
        "visit_duration_hours": 6.0,
        "entry_fee_usd": 0,
        "best_time": "morning",
        "tags": ["beach", "whale watching", "surfing", "relaxation"],
        "description": "Tropical beach famous for whale watching",
        "difficulty": "easy",
        "ocean_traits": ["extraversion", "openness"]
    },
    {
        "id": "unawatuna",
        "name": "Unawatuna Beach",
        "lat": 6.0143,
        "lng": 80.2493,
        "category": "beach",
        "region": "south_coast",
        "visit_duration_hours": 5.0,
        "entry_fee_usd": 0,
        "best_time": "morning",
        "tags": ["beach", "snorkeling", "dining", "nightlife"],
        "description": "Protected bay with calm waters and coral reef",
        "difficulty": "easy",
        "ocean_traits": ["extraversion", "agreeableness"]
    },
    {
        "id": "galle_fort",
        "name": "Galle Fort",
        "lat": 6.0269,
        "lng": 80.2169,
        "category": "cultural",
        "region": "south_coast",
        "visit_duration_hours": 3.0,
        "entry_fee_usd": 0,
        "best_time": "evening",
        "tags": ["history", "colonial", "shopping", "photography", "UNESCO"],
        "description": "Portuguese-built Dutch colonial fort by the sea",
        "difficulty": "easy",
        "ocean_traits": ["openness", "agreeableness"]
    },
    {
        "id": "arugam_bay",
        "name": "Arugam Bay",
        "lat": 6.8396,
        "lng": 81.8369,
        "category": "beach",
        "region": "east_coast",
        "visit_duration_hours": 8.0,
        "entry_fee_usd": 0,
        "best_time": "morning",
        "tags": ["surfing", "beach", "nightlife", "laid-back"],
        "description": "World-class surf spot with relaxed vibes",
        "difficulty": "easy",
        "ocean_traits": ["extraversion", "openness", "neuroticism_low"]
    },
    {
        "id": "trincomalee",
        "name": "Trincomalee & Pigeon Island",
        "lat": 8.5872,
        "lng": 81.2152,
        "category": "beach",
        "region": "east_coast",
        "visit_duration_hours": 6.0,
        "entry_fee_usd": 15,
        "best_time": "morning",
        "tags": ["snorkeling", "diving", "beach", "whale watching"],
        "description": "Clear waters perfect for snorkeling and diving",
        "difficulty": "easy",
        "ocean_traits": ["openness", "extraversion"]
    },
    # Wildlife
    {
        "id": "yala",
        "name": "Yala National Park",
        "lat": 6.3730,
        "lng": 81.5213,
        "category": "wildlife",
        "region": "south",
        "visit_duration_hours": 6.0,
        "entry_fee_usd": 40,
        "best_time": "morning",
        "tags": ["safari", "leopard", "wildlife", "photography"],
        "description": "Sri Lanka's most visited park, highest leopard density",
        "difficulty": "easy",
        "ocean_traits": ["openness", "extraversion", "conscientiousness"]
    },
    {
        "id": "minneriya",
        "name": "Minneriya National Park",
        "lat": 8.0333,
        "lng": 80.9000,
        "category": "wildlife",
        "region": "cultural_triangle",
        "visit_duration_hours": 4.0,
        "entry_fee_usd": 35,
        "best_time": "evening",
        "tags": ["elephant gathering", "wildlife", "safari"],
        "description": "Famous for the 'Gathering' of hundreds of elephants",
        "difficulty": "easy",
        "ocean_traits": ["openness", "agreeableness"]
    },
    {
        "id": "udawalawe",
        "name": "Udawalawe National Park",
        "lat": 6.4385,
        "lng": 80.8985,
        "category": "wildlife",
        "region": "south",
        "visit_duration_hours": 5.0,
        "entry_fee_usd": 35,
        "best_time": "morning",
        "tags": ["elephants", "safari", "wildlife", "birds"],
        "description": "Best place to see wild elephants in Sri Lanka",
        "difficulty": "easy",
        "ocean_traits": ["openness", "agreeableness"]
    },
    # Adventure
    {
        "id": "kitulgala",
        "name": "Kitulgala White Water Rafting",
        "lat": 6.9896,
        "lng": 80.4148,
        "category": "adventure",
        "region": "hill_country",
        "visit_duration_hours": 4.0,
        "entry_fee_usd": 35,
        "best_time": "morning",
        "tags": ["rafting", "adventure", "jungle", "filming"],
        "description": "Thrilling white water rafting on the Kelani River",
        "difficulty": "hard",
        "ocean_traits": ["openness", "extraversion", "conscientiousness_low"]
    },
    {
        "id": "negombo",
        "name": "Negombo Fish Market & Beach",
        "lat": 7.2081,
        "lng": 79.8358,
        "category": "cultural",
        "region": "west_coast",
        "visit_duration_hours": 3.0,
        "entry_fee_usd": 0,
        "best_time": "morning",
        "tags": ["fish market", "beach", "culture", "dutch canal"],
        "description": "Gateway city with lively fish market and colonial history",
        "difficulty": "easy",
        "ocean_traits": ["openness", "extraversion"]
    },
    {
        "id": "colombo",
        "name": "Colombo City Tour",
        "lat": 6.9271,
        "lng": 79.8612,
        "category": "cultural",
        "region": "west_coast",
        "visit_duration_hours": 5.0,
        "entry_fee_usd": 0,
        "best_time": "morning",
        "tags": ["city", "shopping", "food", "museums", "colonial"],
        "description": "Vibrant capital with colonial buildings, malls, and cuisine",
        "difficulty": "easy",
        "ocean_traits": ["extraversion", "openness", "agreeableness"]
    }
]

# Region information
REGIONS = {
    "west_coast": {"name": "West Coast", "base_city": "Colombo"},
    "south_coast": {"name": "South Coast", "base_city": "Galle"},
    "east_coast": {"name": "East Coast", "base_city": "Arugam Bay"},
    "cultural_triangle": {"name": "Cultural Triangle", "base_city": "Dambulla"},
    "hill_country": {"name": "Hill Country", "base_city": "Kandy"},
    "south": {"name": "South", "base_city": "Udawalawe"},
}

# ─────────────────────────────────────────────────────────────────────────────
# HOTELS — Demo data for covered areas only.
# Areas with CSV data: Ahungalla, Anuradhapura, Arugam Bay, Dabulla,
# Dabulla Western Province, Hambantota, Hikkaduwa, Kaluthara, Kandy,
# Kandy-Anuradhapura-Arugam corridor, Mirissa, Negombo,
# Panadura-Wadduwa, Polonnaruwa-Trincomalee-Minneriya corridor,
# Polonnaruwa, Southern Province, Thalpe, Trincomalee, Yala, Yala-Negombo
#
# Each hotel has: name, area, lat, lng, price_per_night (USD), rating, tier
# ─────────────────────────────────────────────────────────────────────────────

HOTEL_AREAS = {
    # area_id : { lat, lng } — used for nearest-area matching
    "ahungalla":       {"lat": 6.3167, "lng": 80.0500},
    "anuradhapura":    {"lat": 8.3114, "lng": 80.4037},
    "arugam_bay":      {"lat": 6.8396, "lng": 81.8369},
    "dambulla":        {"lat": 7.8567, "lng": 80.6490},
    "hambantota":      {"lat": 6.1241, "lng": 81.1185},
    "hikkaduwa":       {"lat": 6.1395, "lng": 80.1062},
    "kalutara":        {"lat": 6.5854, "lng": 79.9607},
    "kandy":           {"lat": 7.2936, "lng": 80.6413},
    "mirissa":         {"lat": 5.9483, "lng": 80.4515},
    "negombo":         {"lat": 7.2081, "lng": 79.8358},
    "panadura":        {"lat": 6.7133, "lng": 79.9053},
    "polonnaruwa":     {"lat": 7.9403, "lng": 81.0188},
    "thalpe":          {"lat": 6.0010, "lng": 80.2290},
    "trincomalee":     {"lat": 8.5872, "lng": 81.2152},
    "yala":            {"lat": 6.3730, "lng": 81.5213},
}

HOTELS = {
    "budget": [
        {"name": "Ahungalla Beach Hostel",         "area": "ahungalla",    "lat": 6.3167, "lng": 80.0500, "price_per_night": 12, "rating": 3.9},
        {"name": "Anuradhapura Rest House",         "area": "anuradhapura", "lat": 8.3114, "lng": 80.4037, "price_per_night": 14, "rating": 3.8},
        {"name": "Arugam Bay Surf Hostel",          "area": "arugam_bay",   "lat": 6.8396, "lng": 81.8369, "price_per_night": 13, "rating": 4.1},
        {"name": "Dambulla Budget Inn",             "area": "dambulla",     "lat": 7.8567, "lng": 80.6490, "price_per_night": 11, "rating": 3.7},
        {"name": "Hambantota Guesthouse",           "area": "hambantota",   "lat": 6.1241, "lng": 81.1185, "price_per_night": 13, "rating": 3.8},
        {"name": "Hikkaduwa Beach Hostel",          "area": "hikkaduwa",    "lat": 6.1395, "lng": 80.1062, "price_per_night": 15, "rating": 4.0},
        {"name": "Kalutara Budget Stay",            "area": "kalutara",     "lat": 6.5854, "lng": 79.9607, "price_per_night": 12, "rating": 3.8},
        {"name": "Kandy Backpackers",               "area": "kandy",        "lat": 7.2936, "lng": 80.6413, "price_per_night": 16, "rating": 4.1},
        {"name": "Mirissa Hostel",                  "area": "mirissa",      "lat": 5.9483, "lng": 80.4515, "price_per_night": 14, "rating": 4.0},
        {"name": "Negombo Beach Hostel",            "area": "negombo",      "lat": 7.2081, "lng": 79.8358, "price_per_night": 15, "rating": 3.9},
        {"name": "Panadura Budget Inn",             "area": "panadura",     "lat": 6.7133, "lng": 79.9053, "price_per_night": 11, "rating": 3.7},
        {"name": "Polonnaruwa Rest House",          "area": "polonnaruwa",  "lat": 7.9403, "lng": 81.0188, "price_per_night": 13, "rating": 3.9},
        {"name": "Thalpe Guesthouse",               "area": "thalpe",       "lat": 6.0010, "lng": 80.2290, "price_per_night": 14, "rating": 3.8},
        {"name": "Trincomalee Budget Stay",         "area": "trincomalee",  "lat": 8.5872, "lng": 81.2152, "price_per_night": 12, "rating": 3.8},
        {"name": "Yala Safari Hostel",              "area": "yala",         "lat": 6.3730, "lng": 81.5213, "price_per_night": 18, "rating": 4.0},
    ],
    "mid": [
        {"name": "Ahungalla Chaaya Tranz Hotel",    "area": "ahungalla",    "lat": 6.3167, "lng": 80.0500, "price_per_night": 95,  "rating": 4.3},
        {"name": "Anuradhapura Palm Garden Village","area": "anuradhapura", "lat": 8.3114, "lng": 80.4037, "price_per_night": 85,  "rating": 4.4},
        {"name": "Arugam Bay Beach Resort",         "area": "arugam_bay",   "lat": 6.8396, "lng": 81.8369, "price_per_night": 80,  "rating": 4.3},
        {"name": "Dambulla Cave Resort",            "area": "dambulla",     "lat": 7.8567, "lng": 80.6490, "price_per_night": 75,  "rating": 4.2},
        {"name": "Hambantota Beach Hotel",          "area": "hambantota",   "lat": 6.1241, "lng": 81.1185, "price_per_night": 90,  "rating": 4.3},
        {"name": "Hikkaduwa Beach Hotel",           "area": "hikkaduwa",    "lat": 6.1395, "lng": 80.1062, "price_per_night": 85,  "rating": 4.4},
        {"name": "Kalutara Tangerine Beach Hotel",  "area": "kalutara",     "lat": 6.5854, "lng": 79.9607, "price_per_night": 100, "rating": 4.4},
        {"name": "Kandy Hills Resort",              "area": "kandy",        "lat": 7.2936, "lng": 80.6413, "price_per_night": 90,  "rating": 4.4},
        {"name": "Mirissa Hills Hotel",             "area": "mirissa",      "lat": 5.9483, "lng": 80.4515, "price_per_night": 85,  "rating": 4.5},
        {"name": "Negombo Beach Hotel",             "area": "negombo",      "lat": 7.2081, "lng": 79.8358, "price_per_night": 80,  "rating": 4.3},
        {"name": "Panadura Eco Resort",             "area": "panadura",     "lat": 6.7133, "lng": 79.9053, "price_per_night": 70,  "rating": 4.1},
        {"name": "Polonnaruwa Heritage Hotel",      "area": "polonnaruwa",  "lat": 7.9403, "lng": 81.0188, "price_per_night": 80,  "rating": 4.3},
        {"name": "Thalpe Fort Boutique Hotel",      "area": "thalpe",       "lat": 6.0010, "lng": 80.2290, "price_per_night": 110, "rating": 4.5},
        {"name": "Trincomalee Beach Hotel",         "area": "trincomalee",  "lat": 8.5872, "lng": 81.2152, "price_per_night": 85,  "rating": 4.3},
        {"name": "Yala Safari Camp",                "area": "yala",         "lat": 6.3730, "lng": 81.5213, "price_per_night": 110, "rating": 4.6},
    ],
    "luxury": [
        {"name": "Ahungalla Heritance Hotel",       "area": "ahungalla",    "lat": 6.3167, "lng": 80.0500, "price_per_night": 380, "rating": 4.8},
        {"name": "Anuradhapura Ulagalla Resort",    "area": "anuradhapura", "lat": 8.3114, "lng": 80.4037, "price_per_night": 420, "rating": 4.9},
        {"name": "Arugam Bay Kottukal Beach House", "area": "arugam_bay",   "lat": 6.8396, "lng": 81.8369, "price_per_night": 300, "rating": 4.7},
        {"name": "Dambulla Amaya Lake",             "area": "dambulla",     "lat": 7.8567, "lng": 80.6490, "price_per_night": 350, "rating": 4.8},
        {"name": "Hambantota Shangri-La",           "area": "hambantota",   "lat": 6.1241, "lng": 81.1185, "price_per_night": 450, "rating": 4.9},
        {"name": "Hikkaduwa Coral Sands Resort",    "area": "hikkaduwa",    "lat": 6.1395, "lng": 80.1062, "price_per_night": 320, "rating": 4.7},
        {"name": "Kalutara Centara Ceysands",       "area": "kalutara",     "lat": 6.5854, "lng": 79.9607, "price_per_night": 400, "rating": 4.8},
        {"name": "Kandy Mahaweli Reach Hotel",      "area": "kandy",        "lat": 7.2936, "lng": 80.6413, "price_per_night": 280, "rating": 4.7},
        {"name": "Mirissa Cape Weligama",           "area": "mirissa",      "lat": 5.9483, "lng": 80.4515, "price_per_night": 500, "rating": 4.9},
        {"name": "Negombo Jetwing Lagoon",          "area": "negombo",      "lat": 7.2081, "lng": 79.8358, "price_per_night": 350, "rating": 4.8},
        {"name": "Panadura Siam House",             "area": "panadura",     "lat": 6.7133, "lng": 79.9053, "price_per_night": 280, "rating": 4.7},
        {"name": "Polonnaruwa Deer Park Hotel",     "area": "polonnaruwa",  "lat": 7.9403, "lng": 81.0188, "price_per_night": 310, "rating": 4.7},
        {"name": "Thalpe Triton Hotel",             "area": "thalpe",       "lat": 6.0010, "lng": 80.2290, "price_per_night": 360, "rating": 4.8},
        {"name": "Trincomalee Jungle Beach Resort", "area": "trincomalee",  "lat": 8.5872, "lng": 81.2152, "price_per_night": 400, "rating": 4.8},
        {"name": "Yala Wild Coast Tented Lodge",    "area": "yala",         "lat": 6.3730, "lng": 81.5213, "price_per_night": 800, "rating": 5.0},
    ]
}

# Local guides
GUIDES = [
    {
        "id": "guide_001",
        "name": "Chamara Perera",
        "specialization": ["cultural_triangle", "wildlife"],
        "languages": ["English", "German", "Sinhala"],
        "rating": 4.9,
        "daily_rate_usd": 60,
        "certified": True,
        "experience_years": 12
    },
    {
        "id": "guide_002",
        "name": "Priya Fernando",
        "specialization": ["hill_country", "south_coast"],
        "languages": ["English", "French", "Sinhala"],
        "rating": 4.8,
        "daily_rate_usd": 55,
        "certified": True,
        "experience_years": 8
    },
    {
        "id": "guide_003",
        "name": "Saman Wickrama",
        "specialization": ["adventure", "east_coast"],
        "languages": ["English", "Sinhala"],
        "rating": 4.7,
        "daily_rate_usd": 50,
        "certified": True,
        "experience_years": 6
    },
    {
        "id": "guide_004",
        "name": "Nimal Jayasena",
        "specialization": ["wildlife", "south"],
        "languages": ["English", "Italian", "Sinhala"],
        "rating": 4.9,
        "daily_rate_usd": 65,
        "certified": True,
        "experience_years": 15
    }
]